name: CI
'on':
  push:
    branches:
      - main
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
- name: Build HTML5 using DITA-OT commands
  uses: dita-ot/dita-ot-action@master
  with:
      install : |
        dita install Docs/dita-ot-doc.css
      build: |
        dita -i Docs/spm_navigation_sample.ditamap -o SPM_HTML5  -f html5 --filter=Docs/cur_spm_test.ditaval:Docs/cur_spm802.ditaval:Docs/cur_base_spm800.ditaval --nav-toc=full --args.copycss=yes
